### ISSUE TITLE
Nightly resources don't appear to be building quite right

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/plumbing#526]
# Expected Behavior

`kustomize build`ing the nightly release yamls works as expected.

# Actual Behavior

At the moment it looks like trying to build the yamls results in invalid TriggerTemplates for pipelines / dashboard / triggers. The `params` field from the `base/template.yaml` are not appearing in the final output.

# Steps to Reproduce the Problem

1. cd into the plumbing repo root directory
2. `kustomize build ./tekton/resources/nightly-release > ./nightly-resources.yaml`
3. Take a look at the generated `TriggerTemplate`s for pipelines, dashboard, triggers
4. The `params` field of the TriggerTemplate is missing.

**Comment by savitaashture** [comment]
@sbwsg I have followed the steps which you have given and when i see TriggerTemplate for triggers-nightly i see `params` exist i don't see any missing field 
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  annotations:
    release: nightly
  labels:
    app: tekton.plumbing
  name: triggers-nightly-release-template
spec:
  params:
  - description: The ID of the build. This is used to build artifact tracking.
    name: buildID
  - description: The Git revision to be used for the release.
    name: gitrevision
  - description: The Git repository to be used for the release.
    name: gitrepository
  - description: The version tag to be applied to published images.
    name: versionTag
  - default: gcr.io/tekton-nightly
    description: Registry where the images will be published to.
    name: imageRegistry
  - description: Name of the Tekton project to release (e.g. pipeline, triggers, etc).
    name: projectName
```
