### ISSUE TITLE
Migrate our Tekton CD folder away from PipelineResources

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/plumbing#887]
### Feature request

The Tasks and Pipelines we currently have in our [`cd`](https://github.com/tektoncd/plumbing/tree/main/tekton/cd) directory utilize Cluster PipelineResources because they provide a way to include cluster secrets that won't expose them in logs.

This issue is to capture work to move away from PipelineResources in the resources from that directory. The current best alternative to the Cluster PipelineResource might be https://github.com/tektoncd/catalog/blob/main/task/kubeconfig-creator/0.1/kubeconfig-creator.yaml although that currently accepts credentials via param which is definitely not a secure approach.

- [x] Folder deployment: https://github.com/tektoncd/plumbing/pull/1157
- [x] Namespace cleanup https://github.com/tektoncd/plumbing/pull/1159
- [x] Configmap deployment https://github.com/tektoncd/plumbing/pull/1160
- [x] Tekton release logs & cleanup unused release resources https://github.com/tektoncd/plumbing/pull/1161
- [x] Helm deployment https://github.com/tektoncd/plumbing/pull/1163
- [ ] Tekton deployment / Install tekton release https://github.com/tektoncd/plumbing/pull/1164

**Comment by afrittoli** [comment]
/lifecycle frozen This is something that need to do in light of the deprecation of pipeline resources

**Comment by afrittoli** [comment]
Tekton resources to convert:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-converter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-creator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "patch", "update"]
- apiGroups: ["tekton.dev"]
  resources: ["PipelineResources"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: resource-converter-secret-creator
subjects:
- kind: ServiceAccount
  name: resource-converter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-creator
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: resource-to-secret
spec:
  params:
    - name: targetSecret
  resources:
    inputs:
      - name: sourceResource
        type: cluster
  stepTemplate:
    env:
      - name: TARGET_SECRET
        value: $(params.targetSecret)
      - name: KUBECONFIG_PATH
        value: /workspace/$(resources.inputs.sourceResource.name)
  steps:
    - name: create-secret
      image: gcr.io/tekton-releases/dogfooding/kubectl
      script: |
        #!/bin/sh
        set -ex

        kubectl create secret generic "${TARGET_SECRET}" \
          --from-file="${KUBECONFIG_PATH}/kubeconfig" \
          --type=kubeconfig

        kubectl label "secret/${TARGET_SECRET}" app=tekton.cd
```
